## **Dataset**

In [1]:
import math
import pandas as pd
import numpy as np
from io import StringIO
from sklearn.preprocessing import MinMaxScaler
from utils import hold_out_validation

problem         = "ML-CUP23"
filename        = f"datasets/ML-CUP/{problem}"
train           = "-TR.csv"
test            = "-TS.csv"

scaler = MinMaxScaler()

def has_nan(lst):
    return any(math.isnan(x) for x in lst)

def reduce_target(y):
    return scaler.fit_transform(y)

def string_dataset_to_float(dataset):
    new_dataset = []
    for i in range(len(dataset)):
        if has_nan(dataset[i]) == False:
            new_dataset.append([float(j) for j in dataset[i]])
    return np.array(new_dataset)

def retrieveData(filename, column_names, column_features):
    data = pd.read_csv(filename, sep=',', header=None, comment="#", names=column_names)
    data=data.iloc[np.random.permutation(len(data))]
    column_names = column_names[1:]
    df_scaled = pd.DataFrame(data.to_numpy(), columns=data.columns.values)
    del df_scaled['id']
    df_train = df_scaled
    features = len(column_features)
    X_train = df_train.iloc[ : , :features].values
    y_train = df_train.iloc[:,features:].values
    #print(column_names)
    X_train = string_dataset_to_float(X_train)
    y_train = string_dataset_to_float(y_train)
    return X_train, y_train

def oneHotEncoding(X_data, l):
    X_result = []
    for x in X_data:
        p = []
        for i in range(len(x)):
            d = [0] * l[i]
            if x[i] == 1:
                d[0] = 1
            elif x[i] == 2:
                d[1] = 1
            elif x[i] == 3:
                d[2] = 1
            elif x[i] == 4:
                d[3] = 1
            p += d
        X_result.append(p)
    return X_result

column_names    = ["id", "i1", "i2", "i3", "i4", "i5", "i6", "i7", "i8", "i9", "i10", "t1", "t2", "t3"]
column_features = ["i1", "i2", "i3", "i4", "i5", "i6", "i7", "i8", "i9", "i10"]
X_train, y_train = retrieveData(filename + train, column_names, column_features)
y_train = reduce_target(y_train)

In [2]:
dataset = hold_out_validation(X_train, y_train)[0]
X_train, y_train, X_test, y_test = dataset["X_train"], dataset['y_train'], dataset['X_val'], dataset['y_val']
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[-0.9853168   0.99746823 -0.9993766  ...  0.8164974   0.7927181
   0.05783666]
 [ 0.9968069  -0.5160568   0.99284256 ...  0.97547317 -0.13245672
  -0.99847734]
 [-0.983089   -0.46261245 -0.9753489  ... -0.31034213  0.29699907
   0.13598575]
 ...
 [-0.8172529   0.9979425  -0.99673223 ...  0.98711556  0.31133792
  -0.8711042 ]
 [ 0.9858918  -0.5736777   0.7343701  ...  0.9934546  -0.755182
  -0.9913831 ]
 [-0.9910794   0.9959111  -0.9994116  ...  0.6746193   0.6658838
   0.50210077]]
[[0.78881432 0.89627873 0.02812261]
 [0.13789905 0.68477026 0.48520789]
 [0.83304108 0.44291335 0.24569648]
 ...
 [0.65098509 0.82844961 0.16369491]
 [0.26351356 0.53797877 0.65780248]
 [0.80444937 0.84173117 0.02525491]]
[[ 0.9003411   0.8406733  -0.3739291  ...  0.99867517 -0.9525439
  -0.95568603]
 [ 0.9461333  -0.78204465  0.987554   ...  0.88559276  0.86754465
  -0.9988826 ]
 [-0.60302955  0.9912961  -0.9875761  ...  0.99291986 -0.871145
  -0.5845758 ]
 ...
 [-0.9950255  -0.530735   -0.94185066 ... -0.

## **Model Selection**

In [3]:
from activation_function import instantiate_act_func
from layer import Layer
from mlp import MLP
from losses import instantiate_loss
from grid_search import create_test
from weigth_init import instantiate_initializer
from utils import k_fold_cross_validation, hold_out_validation
import matplotlib.pyplot as plt
from datetime import datetime
from losses import MeanEuclideanError, MeanSquaredError

In [5]:
filename = "results/model-assessment/ML-CUP23/release/ML-CUP23.pkl"
model = MLP()
model.load(filename)
mse, mse_norm = 0, 0
mee, mee_norm = 0, 0
mee_func, mse_func = MeanEuclideanError(), MeanSquaredError()
for x, y in zip(X_train, y_train):
    out = model.run(x)
    mse += mse_func.error(y, out)
    mee += mee_func.error(y, out)
    mse_norm += mse_func.error(scaler.inverse_transform([y])[0], scaler.inverse_transform([out])[0])
    mee_norm += mee_func.error(scaler.inverse_transform([y])[0], scaler.inverse_transform([out])[0])
print("mee: ", mee/len(X_train))
print("mee norm: ", mee_norm/len(X_train))
print("mse: ", mse/len(X_train))
print("mse norm: ", mse_norm/len(X_train))
    

[<layer.Layer object at 0x13ce4eb60>, <layer.Layer object at 0x13ce4ece0>, <layer.Layer object at 0x13ce4e0b0>]
[array([0.29114539, 0.44705927, 0.18073664, 0.79074835, 0.45271328,
       0.35512569, 0.1095718 , 0.91199158, 0.44501031, 0.76541001,
       0.36030917, 0.83529633, 0.2863806 , 0.68038442, 0.11651642,
       0.5948775 , 0.10101657, 0.49178987, 0.56488001, 0.47257285,
       0.4700636 , 0.53233054, 0.85771958, 0.17491404, 0.72771547,
       0.87680116, 0.38648038, 0.05469677, 0.4168345 , 0.61510744]), array([0.65562612, 0.85176519, 0.7531381 , 0.3163074 , 0.75701923,
       0.38859485, 0.10237442, 0.95497295, 0.93623539, 0.71628708,
       0.07269616, 0.76225283, 0.11894228, 0.93617858, 0.49149533,
       0.54043646, 0.33779737, 0.20651636, 0.68099993, 0.39093159,
       0.8707016 , 0.93090887, 0.33583581, 0.19776352, 0.94605692,
       0.24716897, 0.16308228, 0.97940694, 0.25714394, 0.89483833]), array([0.78228541, 0.89324532, 0.10694709])]
[<layer.Layer object at 0x13ce4eb6

In [ ]:
model_path = "models/ML-CUP"
json_file_config = [
    f"{model_path}/model1.json",
    f"{model_path}/model2.json",
    f"{model_path}/model3.json",
]
tests = create_test(json_file_config)

In [ ]:
def create_model_from_test(test):
    layers = []
    n_processes = None
    for layer in test['layers']:
        layers.append(
            Layer(
                layer['units'],
                instantiate_act_func(layer['act_func']),
                layer['inputs'],
                weights_initializer=instantiate_initializer(test['weights_initializer']),
                kernel_regularizer=test['kernel_regularizer'],
                bias_regularizer=test['bias_regularizer'],
                momentum=test['momentum'],
                Nesterov=test['Nesterov'],
                n_processes=n_processes
            )
        )
    mlp = MLP(layers)
    mlp.compile(test['learning_rate'],instantiate_loss(test['loss']), test['metrics'])
    return mlp

In [ ]:
def save_result(path, test, error, accuracy, summary):
    iso_date = datetime.now().replace(microsecond=0).isoformat()
    filename = f"{path}/{iso_date}-err:{str(round(error, 6))}-mee:{str(round(accuracy, 6))}"
    f = open(f"{filename}.logs", 'w')
    f.write(f"{str(test)}\n")
    f.write(f"{summary}\n")
    f.close()

In [ ]:
path_model_selection_result = f"results/model-selection/{problem}"

In [ ]:
def plot_chart(path, tr_res, vl_res, tr_label, vl_label, y_label):
    iso_date = datetime.now().replace(microsecond=0).isoformat()
    plt.plot(tr_res, label=tr_label, color='blue')
    plt.plot(vl_res, label=vl_label, color='red', linestyle='--')
    plt.xlabel('Epochs')
    plt.ylabel(y_label)
    plt.legend()
    filename = f"{path}/{iso_date}-{y_label}"
    plt.savefig(f'{filename}.png')
    plt.show()

In [ ]:
from tqdm import trange
best_test = None
best_inst_model = None
best_error = 1000
for test in tests:
    epochs = test['epochs']
    model = create_model_from_test(test)
    dataset = hold_out_validation(X_train, y_train)
    print(test)
    tr_errors = []
    vl_errors = []
    tr_accuracies = []
    vl_accuracies = []
    for fold in dataset:
        bar = trange(epochs)
        for _ in bar:
            tr_error, tr_accuracy = model.fit(fold['X_train'], fold['y_train'], 1)
            vl_error, vl_accuracy = model.evaluate(fold['X_val'], fold['y_val'])
            tr_errors.append(tr_error[0])
            vl_errors.append(vl_error)
            tr_accuracies.append(tr_accuracy[0])
            vl_accuracies.append(vl_accuracy)
            bar.set_description(f'(loss={vl_error})')
        summary = model.summary()


    error = vl_errors[-1]
    accuracy = vl_accuracies[-1]

    if best_error > error:
        best_error = error
        best_test = test
        best_inst_model = model

    save_result(path_model_selection_result, test, error, accuracy, summary)
    plot_chart(path_model_selection_result, tr_errors, vl_errors, "Train Error", "Valid Error", "Error")
    plot_chart(path_model_selection_result, tr_accuracies, vl_accuracies, "Train MEE", "Valid MEE", "MEE")

## **Model Assessment**

In [ ]:
path_model_assessment_result = f"results/model-assessment/{problem}"
model = create_model_from_test(best_test)
tr_errors = []
vl_errors = []
tr_accuracies = []
vl_accuracies = []
bar = trange(best_test['epochs'])
for _ in bar:
    tr_error, tr_accuracy = model.fit(X_train, y_train, 1)
    vl_error, vl_accuracy = model.evaluate(X_test, y_test)
    tr_errors.append(tr_error[0])
    vl_errors.append(vl_error)
    tr_accuracies.append(tr_accuracy[0])
    vl_accuracies.append(vl_accuracy)
summary = model.summary()

save_result(path_model_assessment_result, best_test, vl_error, vl_accuracy, summary)
plot_chart(path_model_assessment_result, tr_errors, vl_errors, "Train Error", "Valid Error", "Error")
plot_chart(path_model_assessment_result, tr_accuracies, vl_accuracies, "Train MEE", "Valid MEE", "MEE")

In [ ]:
model.save(path_model_assessment_result)

In [ ]:
from losses import MeanEuclideanError
l = MeanEuclideanError()
global_error = 0
global_error_transform = 0

for i in range(len(X_train)):
    out = model.run(X_train[i])
    global_error += l.error(out, y_train[i])
    global_error_transform += l.error(scaler.inverse_transform([out]), scaler.inverse_transform([y_train[i]]))
print(global_error/len(X_train))
print(global_error_transform/len(X_train))

In [ ]:
l = MeanSquaredError()
global_error = 0
for i in range(len(X_test)):
    out = model.run(X_test[i])
    print(scaler.inverse_transform([out]))

# **Compute Results**

In [ ]:
import math
import pandas as pd
import numpy as np
from io import StringIO
from sklearn.preprocessing import MinMaxScaler
from utils import hold_out_validation

problem         = "ML-CUP23"
filename        = f"datasets/ML-CUP/{problem}"
test            = "-TS.csv"


def has_nan(lst):
    return any(math.isnan(x) for x in lst)

def string_dataset_to_float(dataset):
    new_dataset = []
    for i in range(len(dataset)):
        if has_nan(dataset[i]) == False:
            new_dataset.append([float(j) for j in dataset[i]])
    return np.array(new_dataset)

def retrieveData(filename, column_names, column_features):
    data = pd.read_csv(filename, sep=',', header=None, comment="#", names=column_names)
    data=data.iloc[np.random.permutation(len(data))]
    df_scaled = pd.DataFrame(data.to_numpy(), columns=data.columns.values)
    df_train = df_scaled
    X_train = df_train.iloc[ : , :].values
    X_train = string_dataset_to_float(X_train)
    return X_train

def oneHotEncoding(X_data, l):
    X_result = []
    for x in X_data:
        p = []
        for i in range(len(x)):
            d = [0] * l[i]
            if x[i] == 1:
                d[0] = 1
            elif x[i] == 2:
                d[1] = 1
            elif x[i] == 3:
                d[2] = 1
            elif x[i] == 4:
                d[3] = 1
            p += d
        X_result.append(p)
    return X_result

column_names    = ["id", "i1", "i2", "i3", "i4", "i5", "i6", "i7", "i8", "i9", "i10"]
column_features = ["id", "i1", "i2", "i3", "i4", "i5", "i6", "i7", "i8", "i9", "i10"]
X_test = retrieveData(filename + test, column_names, column_features)

In [ ]:
for x in X_test:
    print(x[0])

In [ ]:
team = "team-name_ML-CUP23-TS.csv"
path_result = f"results/model-assessment/ML-CUP23/{team}"
l = MeanSquaredError()
f = open(path_result, "w")

for x in X_test:
    out = model.run(x[1:])
    res = scaler.inverse_transform([out])
    res = [str(i) for i in res[0]]
    string = f"{str(x[0])}, " + ", ".join(res)
    f.write(string + "\n")
f.close()